# **NumPy**
NumPy (Numerical Python) adalah package dasar untuk melakukan komputasi di Python. Banyak library komputasi yang dibangun berdasarkan package NumPy, seperti Pandas, Scikit-Learn, Matplotlib, dll.

NumPy juga merupakan `array` multidimensi yang diindeks oleh
`tuple` atau pasangan bilangan bulat positif. Dalam NumPy dimensi disebut
sebagai `axis`, dan banyaknya `axis` disebut `rank`. Sebagai contoh, koordinat
sebuah titik diruang 3D dinyatakan sebagai `[1,2,1]` yang merupakan sebuah `array` dengan `rank 1` karena terdiri dari satu axis. Sedangkan panjang
`axis` tersebut adalah 3.


Cara install sebuah library atau package

In [1]:
pip install numpy

## **Membuat Array**

`array` NumPy disebut sebagai ndarray, atau dikenal juga dengan sebutan
array. Catat bahwa numpy.array tidak sama dengan array Standard Python
array.array, yang hanya bisa digunakan untuk array satu dimensi dan
dengan fitur yang lebih sedikit. Atribut yang paling penting dari ndarray
adalah:
> **ndarray.ndim** banyaknya axis atau dimensi dari array. Di Python, banyaknya dimensi disebut sebagai `rank`.

> **ndarray.shape** dimensi dari array. Ini adalah pasangan bilangan bulat yang
menunjukkan ukuran array di setiap dimensi. Untuk matriks
dengan n baris dan m kolom, bentuknya adalah `(n, m)`. Panjang
dari pasangan shape adalah `rank`, atau jumlah dimensi, `ndim`.

> **ndarray.size** jumlah elemen dari array. Ini sama dengan perkalian elemen
dari shape.

> **ndarray.dtype** sebuah objek yang menggambarkan jenis elemen dalam array. Seseorang dapat membuat atau menentukan jenis dtype
menggunakan jenis Python standar. Selain itu NumPy menyediakan jenisnya sendiri. `numpy.int32`, `numpy.int16`, dan `numpy.float64`
adalah beberapa contohnya.

> **ndarray.itemsize** ukuran dalam byte dari setiap elemen array. Sebagai contoh, sebuah array dari elemen tipe `float64` memiliki itemsize 8
(= 64/8), sedangkan satu dari tipe complex32 memiliki itemsize
4 (= 32/8). Ini sama dengan `ndarray.dtype.itemsize`.

> **ndarray.data** buffer yang mengandung elemen sebenarnya dari array. Biasanya, kita tidak perlu menggunakan atribut ini karena kita akan mengakses elemen dalam array menggunakan fasilitas pengindeksan.

In [13]:
import numpy as np
A = np.arange(15).reshape(3, 5)
print(A)

B = np.array([[2,2],[2,2]], dtype="int64") #list
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[2 2]
 [2 2]]


In [21]:
A.ndim

2

In [22]:
A.shape

(3, 5)

In [23]:
A.size

15

In [24]:
A.dtype

dtype('int64')

In [25]:
type(A)

numpy.ndarray

In [26]:
A.itemsize

8